name: voce
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.2+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.3.2
  google_fonts: ^6.1.0
  http: ^1.0.0
  json_annotation: ^4.1.0
  shared_preferences: ^2.0.8
  flutter_advanced_drawer: ^1.2.3
  flex_color_picker: ^3.2.2
  rxdart: ^0.27.2
  reorderables: ^0.6.0 #old 0.4.1
  file_picker: ^5.3.0
  camera: ^0.10.5
  path_provider: ^2.0.5
  path: ^1.8.0
  flutter_typeahead: ^4.3.8
  get_it: ^7.2.0
  avatar_glow:
    git:
      url: https://github.com/apgapg/avatar_glow
      ref: master

  bloc: ^8.0.1
  flutter_bloc: ^8.0.0

  flutter_image_compress: ^2.0.3

  lazy_load_scrollview: ^1.3.0

  flutter_holo_date_picker: ^1.0.1+2

  tuple: ^2.0.0

  flutter_zoom_drawer: ^3.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  speech_to_text: ^6.6.0
  flutter_tts: ^3.4.0
  auto_size_text: ^3.0.0
  expandable: ^5.0.1
  printing: ^5.12.0
  fl_chart: ^0.63.0
  animations: ^2.0.7
  audioplayers: ^5.1.0
  carousel_slider: ^4.2.1
  flutter_reorderable_grid_view: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  dio: ^5.3.3
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  json_serializable: ^6.6.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_voce_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/
      - assets/icons/
      - assets/icons/avatars/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages